version: "3.4"

# Production environment override
services:
  php:
    build:
      args:
        APP_ENV: prod
    environment:
      APP_ENV: prod

  caddy:
    build:
      args:
        APP_ENV: prod
    environment:
      MERCURE_DEMO: # Disable the demo
      MERCURE_PUBLISHER_JWT: ${MERCURE_PUBLISHER_JWT}
      MERCURE_SUBSCRIBER_JWT: ${MERCURE_SUBSCRIBER_JWT}
