version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./:/srv/app:rw,cached
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      # - ./var:/srv/app/var:rw
    environment:
      APP_ENV: dev
    depends_on:
      - database

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/app/public:ro

  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ChangeMe}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - db-data:/var/lib/mysql:rw

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT:-8080}:8080

volumes:
  db-data:
