name: CI

on:
    push:
    pull_request:

jobs:
    coding-standards:
        name: Coding standards
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            - name: Install PHP dependencies (composer install)
              uses: php-actions/composer@v5
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Install JS dependencies (npm install)
              run: npm i --ignore-scripts --production=false
            - name: PHP CS Fixer
              run: DEV/ci/php-cs-fixer.sh
            - name: PHP Stan
              run: DEV/ci/phpstan.sh
            - name: PHP MD
              run: DEV/ci/phpmd.sh
            - name: CSS stylelint
              run: DEV/ci/stylelint.sh
            - name: ESLint (JS)
              run: DEV/ci/eslint.sh

    build:
        name: Docker build and tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Pull images
              run: docker-compose pull
            - name: Prepare auto-rotating cache key for Docker layer caching
              run: echo "WEEK=$(date +%U)" >> $GITHUB_ENV
            - uses: satackey/action-docker-layer-caching@v0.0.11
              continue-on-error: true
              with:
                key: ${{ github.workflow }}-${{ env.WEEK }}-{hash}
                restore-keys: |
                  ${{ github.workflow }}-${{ env.WEEK }}-
            - name: Start services
              run: docker-compose up --build -d
            - name: Wait for services
              run: |
                  UNHEALTHY_ALLOWANCE_LEFT=30
                  while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker-compose ps -q php)")"; do
                    case $status in
                      starting)
                        UNHEALTHY_ALLOWANCE_LEFT=30
                        sleep 1;;
                      healthy)
                        sleep 30
                        exit 0;;
                      unhealthy)
                        if [ $UNHEALTHY_ALLOWANCE_LEFT -eq 0 ]; then
                          exit 1
                        else
                          UNHEALTHY_ALLOWANCE_LEFT=$((UNHEALTHY_ALLOWANCE_LEFT - 1))
                          sleep 3
                        fi;;
                    esac
                  done
                  exit 1
            - name: Check HTTP reachability
              run: curl http://localhost
            - name: Check HTTPS reachability
              run: curl -k https://localhost
            - name: PHPUnit tests
              uses: php-actions/phpunit@v2
              with:
                  configuration: phpunit.xml.dist
                  php_version: 8.0
                  php_extensions: ctype iconv json pcre session simplexml tokenizer
