name: CI

on:
    push:
    pull_request:

jobs:
    coding-standards:
        name: Coding standards
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                php-version: '8.0'
                extension-csv: xsl
            - name: Install PHP dependencies (composer install)
              uses: php-actions/composer@v5
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Install JS dependencies (npm install)
              run: npm i --ignore-scripts --production=false
            - name: PHP CS Fixer
              run: DEV/ci/php-cs-fixer.sh
            - name: PHP Stan
              run: DEV/ci/phpstan.sh
            - name: PHP MD
              run: DEV/ci/phpmd.sh
            - name: Twigcs
              run: DEV/ci/twigcs.sh
            - name: CSS stylelint
              run: DEV/ci/stylelint.sh
            - name: ESLint (JS)
              run: DEV/ci/eslint.sh

    build:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  ini-values: post_max_size=256M, max_execution_time=0
            - name: Use Node.js 15.x
              uses: actions/setup-node@v1
              with:
                node-version: 15.x
            - name: Pull images
              run: docker-compose pull
            - name: Start services
              run: docker-compose up --build -d
            - name: Wait for services
              run: |
                  UNHEALTHY_ALLOWANCE_LEFT=20
                  while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker-compose ps -q php)")"; do
                    case $status in
                      starting)
                        UNHEALTHY_ALLOWANCE_LEFT=20
                        sleep 1;;
                      healthy)
                        exit 0;;
                      unhealthy)
                        if [ $UNHEALTHY_ALLOWANCE_LEFT -eq 0 ]; then
                          docker logs --since="5m" "$(docker-compose ps -q php)"
                          exit 1
                        else
                          UNHEALTHY_ALLOWANCE_LEFT=$((UNHEALTHY_ALLOWANCE_LEFT - 1))
                          sleep 3
                        fi;;
                    esac
                  done
                  exit 1
            - name: Check HTTP reachability
              run: curl http://localhost
            - name: Check HTTPS reachability
              run: curl -k https://localhost
            - name: Install JS testing dependencies
              run: npm ci
            - name: Build JS assets with Webpack Encore
              run: npm run encore prod
            - name: Install Playwright dependencies
              run: npx playwright install-deps
            - name: Install Playwright browsers
              run: npx playwright install
            - name: Run tests
              run: ./DEV/ci/run-tests.php --verbose
