name: Production deployment

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment request to production server
        run: |
          curl --data "access_key=${{ secrets.PRODUCTION_DEPLOYMENT_ACCESS_KEY }}" --url "${{ secrets.PRODUCTION_DEPLOYMENT_URL }}"
